// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://labiskxwofphnalurvem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhYmlza3h3b2ZwaG5hbHVydmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MzAxMTksImV4cCI6MjA3MTUwNjExOX0.zDnoR-ZV0wMo2-QUVZnoqH05oTHnoEJc-nBTs8H07Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});